[tool.ruff]
extend-exclude = ["cmake"]

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]
extend-ignore = ["RUF012"]

[tool.ruff.lint.isort]
known-first-party = ["crocoddyl"]

[tool.tomlsort]
all = true
